export const actionStrings = {
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  authRegister: "AUTH_REGISTER",
  authForgot: "AUTH_FORGOT_PASSWORD",
  authReset: "AUTH_RESET_PASSWORD",
  userDetail: "USER_GET_DETAIL",
  userCheckPin: "USER_CHECK_PIN",
  userEditProfile: "USER_EDIT_PROFILE",
  userEditPhone: "USER_EDIT_PHONE",
  userEditImage: "USER_EDIT_IMAGE",
  userEditPin: "USER_EDIT_PIN",
  userEditPassword: "USER_EDIT_PASSWORD",
  userDeleteImage: "USER_DELETE_IMAGE",
  transactionHistory: "GET_TRANSACTIONS_HISTORY",
};
